version: "3.6"
services:
  web:
    build: .
    environment:
      - FLASK_ENV=development
    ports:
      - 8001:8001
  mongodb:
    image: mongo:latest
    container_name: "mongod"
    environment:
      - MONGO_DATA_DIR=/usr/data/db
      - MONGO_LOG_DIR=/dev/null
    volumes:
      - ./data/db:/usr/data/db
    ports:
      - 27017:27017
    command: mongod --smallfiles --logpath=/dev/null
networks:
  default:
    name: web
